export const types = {
  FILL_POSTS: 'FILL_POSTS',
  CREATE_POST: 'CREATE_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  CLEAR_POSTS: 'CLEAR_POSTS',
  REMOVE_POST: 'REMOVE_POST',
  LIKE_POST: 'LIKE_POST',
  LIKE_POST_ASYNC: 'LIKE_POST_ASYNC',
  UNLIKE_POST: 'UNLIKE_POST',
  UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',
  REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
  CREATE_POST_ASYNC: 'CREATE_POSTS_ASYNC',
};
