export const types = {
  AUTHENTICATE: 'AUTHENTICATE',
  INITIALIZE: 'INITIALIZE',
  SIGN_UP_ASYNC: 'SIGN_UP_ASYNC',
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
  INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',
};
